language: generic 
sudo: required
services:
    - docker
    
before_install:
    - docker run -e CI=true sergeialbrant/docker-react npm run test

script:
    - docker run sergeialbrant/docker-react npm run test -- --coverage