language: generic 
sudo: required
services:
    - docker
    
before_install:
    - docker build -t sergeialbrant/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sergeialbrant/docker-react npm run test